name: Poll Tracker
on:
  workflow_dispatch:
    inputs:
      disabled:
        description: "Workflow disabled"
        required: false
        default: "true"

jobs:
  disabled:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Workflow is disabled"
